version: '3.8'

services:
  c1:
    build:
      context: ./Ubuntu_16.10
      dockerfile: Dockerfile
    container_name: c1

  c2:
    build:
      context: ./Ubuntu_18.10
      dockerfile: Dockerfile
    container_name: c2

  c3:
    build:
      context: ./Ubuntu_20.10
      dockerfile: Dockerfile
    container_name: c3

  replica:
    build:
      context: ./Replica_paso2
      dockerfile: Dockerfile
    container_name: replica

  s1:
    build:
      context: ./Ubuntu_22.10
      dockerfile: Dockerfile
    container_name: s1_c4
    ports:
      - "2222:22"